### ISSUE TITLE
Stop requesting to "Have full, unrestricted access to Thunderbird, and your computer"

### ISSUE THREAD

**Issue by 7wells** [dreadnaut/bordercolors-d#22]
Hello!

Currently, bordercolors-d needs "[full, unrestricted access to Thunderbird, and your computer](https://support.mozilla.org/de/kb/permission-request-messages-thunderbird-extensions#w_have-full-unrestricted-access-to-thunderbird-and-your-computer)" (like many other useful and great TB extensions), Is it possible (mid-term) to change that?

Explanation from Mozilla:

> The extension is using an older technology and has full access to Thunderbird’s internal APIs and does not need to request individual permissions. Up to Thunderbird 68 almost every add-on had this unrestricted access without specifically asking for it. Add-ons request this permission, **as long as the new permission based API system does not yet offer the functionality they need**. ...

So do I understand it correctly that as of now, the new permission based API system of TB does not offer the functionality needed by bordercolors-d?

**Comment by dreadnaut** [comment]
Hi there! You are correct, we currently need one piece of functionality that is not available via the new extension API. However, what is missing is not a new functionality, but an old one.

The reason why BorderColors-D still requests "full access" is to [read old-style add-on preferences](https://github.com/dreadnaut/bordercolors-d/blob/master/manifest.json#L34), so that it can migrate the user's configuration from old-Thunderbird and old-BorderColors to the current version. My plan is to wait until only a few users are left on the old versions, and then remove the preferences migration code. The add-on is ready to request [minimal permissions](https://github.com/dreadnaut/bordercolors-d/blob/50b250d7dd9b8a575f548c76706a48a9856fde96/manifest.json#L20).

In practice, I am waiting for the "1.4.0" line in these stats to decrease futher—or stop decreasing.
![image](https://user-images.githubusercontent.com/584584/112517996-e1eaca80-8d90-11eb-8840-c977034eaf39.png)

I understand that "full access" sounds (and is) ominous, and I'll be relieved when I can drop that code. For those who want to be safe, the source code for the add-on is not obfuscated in any way. One can always download the `.xpi` from the Thunderbird Add-ons page, and look inside (it's a zip file) to see what is happening. Always install add-ons from the official website!

**Comment by 7wells** [comment]
Thank you so much - sounds great! :)

**Comment by dreadnaut** [comment]
I have removed the migration code for legacy preferences, and the backward compatibility code that required "full permissions".

The [new release](https://github.com/dreadnaut/bordercolors-d/releases/tag/v2021.9.1) should be live soon.
