### ISSUE TITLE
Make 'Color selectors' window scrollable.

### ISSUE THREAD

**Issue by akwala** [dreadnaut/bordercolors-d#7]
The height of the 'Color selectors' window seems to depend on the the number of defined identities. The window apparently accommodates all the defined identities plus any UI elements like buttons. This causes the window to extend past the display border but there is no way to scroll. This makes it impossible to save the border colors.

This window should at least be scrollable, and preferably also resizable with a sticky size.

**Comment by dreadnaut** [comment]
Ah, that's a regression from the update for TB68!

Thanks for spotting it, I'll make sure it's scrollable again. And possibly manually resizeable.

**Comment by dreadnaut** [comment]
Hey @akwala, the issue should be fixed in v1.4.0. I didn't find a way to make the window resizable (it should already be!) but I made the list scroll it contains several lines.

The add-on should auto-update in the next days, or you can download the [new version](https://github.com/dreadnaut/bordercolors-d/releases/tag/v1.4.0) manually.
